# config.yaml
paths:
  models_root: backend/resources/models
  tokenizer_dir: backend/resources/models/tokenizer
  onnx_model: backend/resources/models/model.onnx
  yolo_weights: backend/resources/models/LP-detection.pt

redaction:
  style: box
  log_provenance: true


# Model settings
model:
  path: backend/resources/models/LP-detection.pt

# Input/Output directory
io:
  input_dir: backend/resources/images
  results_img_dir: backend/results/images
  results_rpt_dir: backend/results/reports

# OCR settings
ocr:
  # Set tesseract_cmd to the path of your Tesseract executable
  # For example, on Windows it might be in the "Program Files" folder
  tesseract_cmd: "C:/Program Files/Tesseract-OCR/tesseract.exe"
  config: "--psm 6"
  conf_threshold: 0 # minimum confidence score to accept word

# PII patterns (regex)
patterns:
  SG_NRIC_FIN: "\\b[STFG]\\d{7}[A-Z]\\b"
  PASSPORT_GENERIC: "\\b[A-Z]{2}\\d{7}\\b"
  GEN_ID: "\\b(?=[A-Z0-9]{6,12}\\b)(?:.*\\d.*\\d)[A-Z0-9]+\\b"