[project]
name = "bleep"
version = "0.1.0"
requires-python = ">=3.11,<3.12"

dependencies = [
    "opencv-python==4.12.0.88",
    "torch==2.8.0",
    "ultralytics==8.3.172"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
